JobManager/Models/Db/RxJob.cs
using System;

namespace JobManager.Models.Db
{
    public partial class RxJob
    {
        public Guid Id { get; set; }
        public int? ContractorId { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public int? Floor { get; set; }
        public int? Room { get; set; }
        public string DelayReason { get; set; }
        public DateTime? DateCreated { get; set; }
        public DateTime? DateCompleted { get; set; }
        public DateTime? DateDelayed { get; set; }
        public int? StatusNum { get; set; }
        public int? RjobId { get; set; }
        public Guid? RoomTypeId { get; set; }
    }
}

JobManager/Models/Db/RxRoomType.cs
using System;
using System.Collections.Generic;

namespace JobManager.Models.Db
{
    public partial class RxRoomType
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

JobManager/Models/ErrorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JobManager.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

JobManager/Models/JobModel.cs
using JobManager.Constant;
using System;

namespace JobManager.Models
{
    public class JobModel
    {
        public string JobID { get; set; }

        public string Name { get; set; }
        public int? Floor { get; set; }
        public string JobStatus { get; set; }
        public string RoomType { get; set; }

        public string StatusColor
        {
            get
            {
                if (string.IsNullOrWhiteSpace(JobStatus))
                    return "table-light";


                if (string.Equals(JobStatus, ConstantText.StatusInProgress, StringComparison.InvariantCultureIgnoreCase))
                {
                    return "table-primary";
                }
                else if (string.Equals(JobStatus, ConstantText.StatusNotStarted, StringComparison.InvariantCultureIgnoreCase))
                {
                    return "table-light";
                }
                else if (string.Equals(JobStatus, ConstantText.StatusCompleted, StringComparison.InvariantCultureIgnoreCase))
                {
                    return "table-success";
                }
                else if (string.Equals(JobStatus, ConstantText.StatusDelayed, StringComparison.InvariantCultureIgnoreCase))
                {
                    return "table-danger";
                }

                return "table-light";
            }
        }

        public bool IsMarkable
        {
            get
            {
                if (string.IsNullOrWhiteSpace(JobStatus))
                    return false;

                if (string.Equals(JobStatus, ConstantText.StatusInProgress, StringComparison.InvariantCultureIgnoreCase) ||
                    string.Equals(JobStatus, ConstantText.StatusDelayed, StringComparison.InvariantCultureIgnoreCase))
                    return true;

                return false;
            }
        }
    }
}

JobManager/Models/Settings/ConnectionString.cs
using Newtonsoft.Json;

namespace JobManager.Models.Settings
{
    public class ConnectionString
    {
        [JsonProperty("defaultConnectionString")]
        public string DefaultConnectionString { get; set; }
    }
}

JobManager/Controllers/API/JobSummaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using JobManager.DataBaseContext;
using JobManager.Models.Settings;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace JobManager.Controllers.API
{
    [Route("v0/api/JobSummary")]
    [ApiController]
    public class JobSummaryController : ControllerBase
    {
        private readonly ILogger<JobSummaryController> _logger;
        private readonly ConnectionString _connectionString;

        public JobSummaryController(IOptions<ConnectionString> options, ILogger<JobSummaryController> logger)
        {
            _logger = logger;
            _connectionString = options.Value;
        }

        [HttpGet("getJobStatusSummary", Name = nameof(GetJobStatusSummary))]
        public IActionResult GetJobStatusSummary()
        {
            var result = new List<object>();

            try
            {
                
                using (var context = new DemoContext(_connectionString.DefaultConnectionString))
                {
                    var roomTypes = context.RxRoomType.ToList();

                    foreach (var status in context.RxJob.ToList().GroupBy(_ => _.Status))
                    {
                        foreach (var subGroup in status.ToList().GroupBy(_ => _.RoomTypeId))
                        {
                            result.Add(new
                            {
                                Status = status.Key,
                                RoomType = roomTypes.FirstOrDefault(_=>_.Id ==  subGroup.Key)?.Name,
                                StatusCount = subGroup.Count()
                            });
                        }
                    }
                }

                return Ok(result);
            }
            catch(Exception ex)
            {
                _logger.LogError(ex, $"Error while trying to crete room status summary - {ex.Message}");

                return StatusCode(500, $"Error while trying to crete room status summary");
            }
        }
    }
}

JobManager/Controllers/MVC/JobController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using JobManager.Models;
using JobManager.DataBaseContext;
using JobManager.Constant;
using Microsoft.Extensions.Options;
using JobManager.Models.Settings;

namespace JobManager.Controllers
{
    public class JobController : Controller
    {
        private readonly ILogger<JobController> _logger;
        private readonly ConnectionString _connectionString;
        public JobController(IOptions<ConnectionString> options, ILogger<JobController> logger)
        {
            _logger = logger;
            _connectionString = options.Value;
        }

        public IActionResult Index()
        {
            try
            {
                using (var context = new DemoContext(_connectionString.DefaultConnectionString))
                {
                    var model =
                        from j in context.RxJob
                        join r in context.RxRoomType on j.RoomTypeId equals r.Id
                        select new JobModel()
                        {
                            JobID = j.Id.ToString(),
                            Name = j.Name,
                            Floor = j.Floor,
                            JobStatus = j.Status,
                            RoomType = r.Name
                        };

                    return View(model.ToList());
                }
            }
            catch(Exception ex)
            {
                _logger.LogError(ex, $"{nameof(MarkCompleted)} - Error while trying to fetch Job data from database.");

                return View(new List<JobModel>());
            }
        }

        public IActionResult MarkCompleted(string jobId)
        {
            try
            {
                if(string.IsNullOrEmpty(jobId) || !Guid.TryParse(jobId, out Guid guid))
                    return new JsonResult(new { success = false, error = ConstantText.ErrorInvalidJobId });

                using (var context = new DemoContext(_connectionString.DefaultConnectionString))
                {
                  var toBeUpdated = context.RxJob.FirstOrDefault(_ => _.Id == guid);

                    if (toBeUpdated != null)
                    {
                        toBeUpdated.Status = ConstantText.StatusCompleted;
                        context.SaveChanges();
                    }
                    else
                    {
                        return new JsonResult(new { success = false, error = ConstantText.ErrorNoJobWasFound });
                    }
                }

                return new JsonResult(new { success = true, id = jobId});
            }
            catch(Exception ex)
            {
                _logger.LogError(ex, $"{nameof(MarkCompleted)} - Error while trying to Update job status.");

                return new JsonResult(new { success = false, error = ex.Message});
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

JobManager/Views/Job/Index.cshtml
@{
    ViewData["Title"] = "Job Manager";
}

@model IEnumerable<JobModel>

<div>
    <div id="spinnerInputSectionContainer" style="display:none;" class="spinner-border" role="status">
        <span class="sr-only">Loading...</span>
    </div>
    <table class="table table-borderless table-striped table-sm">
        <thead class="sticky-top bg-white">
            <tr>
                <th scope="col">Job ID</th>
                <th scope="col">Name</th>
                <th scope="col">Floor</th>
                <th scope="col">Job Status</th>
                <th scope="col">RoomType</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr id="idRow_@item.JobID" class="@item.StatusColor">
                    <td>@item.JobID</td>
                    <td>@item.Name</td>
                    <td>@item.Floor</td>
                    <td id="idStatus_@item.JobID">@item.JobStatus</td>
                    <td>@item.RoomType</td>
                    <td>
                        @if (item.IsMarkable)
                        {
                            <div class="d-flex justify-content-between">
                                <div class="d-flex" style="font-size:small">
                                    <a id="idMarkButtonId_@item.JobID" href="#" title="Delete" onclick="$(this).children().first().submit()">
                                        Mark
                                        <form asp-controller="Job" asp-action="MarkCompleted" method="post"
                                              data-ajax="true"
                                              data-ajax-method="post"
                                              data-ajax-loading="#idSpinner_@item.JobID"
                                              data-ajax-success="jobStatusChanged">
                                            @Html.AntiForgeryToken()
                                            @Html.Hidden("jobId", item.JobID)
                                        </form>
                                    </a>
                                </div>
                                <div id="idSpinner_@item.JobID" class="spinner-border spinner-border-sm" style="display:none;" role="status">
                                    <span class="sr-only">Loading...</span>
                                </div>
                            </div>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts {
    <script>
        $(function () {

            jobStatusChanged = function (xhr) {
                if (xhr.success) {
                    changeStatusAndHideButton(xhr.id);
                }
                else {
                    alert(xhr.error);
                }
            };

            changeStatusAndHideButton = function (id) {
                $('#idMarkButtonId_' + id).hide();
                $('#idRow_' + id).removeClass("table-danger");
                $('#idRow_' + id).removeClass("table-primary");
                $('#idRow_' + id).addClass("table-success");
                $('#idStatus_' + id).html('Complete');
            }
        });
    </script>
}

JobManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JobManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Job" asp-action="Index">JobManager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>